aws:
  region: us-east-1
  endpoint_url: http://localstack:4566
  allow_unsafe_aws_endpoint_urls: true
  credentials:
    secretName: ack-lambda-aws-creds
    secretKey: credentials
    profile: default

reconcile:
  defaultResyncPeriod: 90
