apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: sample-function
  namespace: default
spec:
  name: sample-function
  runtime: python3.13
  handler: handler.handler
  packageType: Zip
  role: arn:aws:iam::000000000000:role/lambda-poc-role
  code:
    s3Bucket: poc-lambda-artifacts
    s3Key: handler-6d6f000.zip
    sha256: jbQ35Q+lAaSgLl39ixw0mY4mgh8OWQrsJZNasy8JX90=
  memorySize: 128
  timeout: 3
