apiVersion: v1
kind: Secret
metadata:
  name: gitops-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/luis-pabon-tf/argo-ack-poc-gitops.git
  username: x-access-token
  password: __PAT_PLACEHOLDER__
